services:
  db:
    image: postgres:16-bookworm
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  backend:
    image: nanaminakano/nextstop-backend
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db:5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
