name: Gradle Test
on:
  pull_request:
  push:
    branches: [ "dev" ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16-bookworm
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: test
        env:
          POSTGRES_DATABASE: postgres
          POSTGRES_HOST: localhost:5432
          POSTGRES_PASSWORD: example
          POSTGRES_USER: postgres
